#:kivy 2.3
# Layout file for main controller

<MenuScreen>:
    BoxLayout: 
        orientation: 'vertical'

        Label: 
            text: 'Main Menu'
            bold: True
            font_size: '24dp'
            size_hint_y: None
            height: '50dp'

        ScrollView: 
            doScrollX: False
            doScrollY: True

            GridLayout:
                cols: 1
                spacing: '20dp'
                size_hint_y: None
                height: self.minimum_height

                Button: 
                    size_hint_y: None
                    text: 'Create a set'
                    height: '100dp'
                    on_release: 
                        root.manager.transition.direction = 'left'
                        root.manager.current = 'editSet'

                Button: 
                    size_hint_y: None
                    text: 'Import a set'
                    height: '100dp'
                    on_release:
                        root.open_filechooser()

                Button: 
                    size_hint_y: None
                    text: 'Delete a set'
                    height: '100dp'
                    on_release: 
                        root.delete_csv()

                Button:
                    size_hint_y: None
                    text: 'View Sets'
                    height: '100dp'
                    on_release:
                        root.manager.transition.direction = 'right'
                        root.manager.current = 'viewSet'