#:kivy 2.3
# Definition for EditScreen

<Button>:
    width: self.texture_size[0]
    padding: '20dp'

<MenuBtn@Button>:
    size_hint: None, 0.8

<TermWidget>: # @BoxLayout
    orientation: 'horizontal'
    size_hint_y: None
    height: self.minimum_height
    spacing: '10dp'

    TermTextInput: 
        id: termfield
        size_hint_y: None
        height: self.font_size + dp(15)
        pos_hint: { 'top': 1 }
        multiline: False
        focus_next: defnfield
        write_tab: False

    TermTextInput: 
        id: defnfield
        size_hint_y: None
        height: self.font_size*3 + dp(15)
        pos_hint: { 'top': 1 }
        multiline: True
        write_tab: False

    Button: 
        id: delbtn
        size_hint: None, None
        pos_hint: { 'x': 0, 'center_y': 0.5 }
        background_normal: 'assets/noun-trash-8055549.png'
        background_down: 'assets/noun-trash-8055549.png'
        width: '30dp'
        height: '30dp'
        on_release: root.get_editor().delete_card(root)

<EditScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: '10dp'

        FloatLayout: 
            id: menubar
            orientation: 'horizontal'
            size_hint_y: None
            height: '50dp'
            padding: '20dp'

            MenuBtn: 
                text: 'Back to menu'
                pos_hint: { 'x': 0, 'center_y': 0.5}
                on_release: 
                    root.manager.transition.direction = 'right'
                    root.manager.current = 'menu'

            BoxLayout: 
                id: menubarright
                orientation: 'horizontal'
                pos_hint: { 'right': 1, 'center_y': 0.6 }
                size_hint_x: None
                width: self.minimum_width
                spacing: '10dp'

                MenuBtn: 
                    text: 'Import'

                MenuBtn: 
                    text: 'Save'
            
            Label: 
                text: 'Edit a set'
                bold: True
                font_size: '24dp'
                size_hint_x: None
                width: self.texture_size[0]
                padding: '20dp'
                pos_hint: { 'center_x': 0.5, 'center_y': 0.5}

        ScrollView: 
            doScrollX: False
            doScrollY: True

            BoxLayout:
                id: content
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: '20dp'

                Widget: 
                    id: topspacer
                    size_hint_y: None
                    height: '10dp'

                GridLayout: 
                    id: topmatter
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: '20dp'

                    BoxLayout: 
                        id: titledesc
                        orientation: 'vertical'
                        size_hint_y: None
                        height: self.minimum_height
                        spacing: '15dp'

                        Label: 
                            text: 'Title:'
                            text_size: self.size
                            halign: 'left'
                        TextInput: 
                            id: titlefield
                            size_hint_y: None
                            height: self.font_size + dp(15)
                            multiline: False
                            write_tab: False
                            focus_next: descfield
                        Label: 
                            text: 'Description:'
                            text_size: self.size
                            halign: 'left'
                        TextInput: 
                            id: descfield
                            size_hint_y: None
                            height: self.font_size * 3 + dp(15)
                            multiline: True
                            write_tab: False

                    Label: 
                        text: 'Properties:'
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'

                BoxLayout: 
                    id: termheaders
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: '20dp'

                    Label:
                        text: 'Term'
                    Label: 
                        text: 'Definition'

                BoxLayout: 
                    id: termlayout
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: '20dp'

                Button: 
                    text: 'Add a card'
                    size_hint: None, None
                    height: self.font_size + dp(25)
                    padding: dp(20)
                    pos_hint: { 'center_x': 0.5}
                    on_release: root.add_card()

                Button: 
                    text: 'Save'
                    size_hint: None, None
                    height: self.font_size + dp(25)
                    padding: dp(20)
                    pos_hint: { 'right': 1 }