#:kivy 2.3
# Definition for EditScreen

<Button>:
    width: self.texture_size[0]
    padding: '20dp'

<MenuBtn@Button>:
    size_hint: None, 0.8

<TermWidget>:
    # BoxLayout:
    orientation: 'horizontal'
    size_hint_y: None
    height: self.minimum_height
    spacing: '20dp'

    TextInput: 
        text: 'Term goes here'
        size_hint_y: None
        height: self.font_size + dp(15)
        pos_hint: { 'top': 1 }
        multiline: False

    TextInput: 
        text: 'Definition goes here'
        size_hint_y: None
        height: self.font_size*3 + dp(15)
        multiline: True

<EditScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: '10dp'

        FloatLayout: 
            orientation: 'horizontal'
            size_hint_y: None
            height: '50dp'
            padding: '20dp'

            MenuBtn: 
                text: 'Back to menu'
                pos_hint: { 'x': 0, 'center_y': 0.5}
                on_release: 
                    root.manager.transition.direction = 'right'
                    root.manager.current = 'menu'

            BoxLayout: 
                orientation: 'horizontal'
                pos_hint: { 'right': 1, 'center_y': 0.6 }
                size_hint_x: None
                width: self.minimum_width
                spacing: '10dp'

                MenuBtn: 
                    text: 'Import'

                MenuBtn: 
                    text: 'Save'
            
            Label: 
                text: 'Edit a set'
                bold: True
                font_size: '24dp'
                size_hint_x: None
                width: self.texture_size[0]
                padding: '20dp'
                pos_hint: { 'center_x': 0.5, 'center_y': 0.5}

        ScrollView: 
            doScrollX: False
            doScrollY: True

            BoxLayout:
                id: content
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: '20dp'

                BoxLayout: 
                    id: termlayout
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: '20dp'

                Button: 
                    text: 'Add a card'
                    size_hint: None, None
                    height: self.font_size + dp(25)
                    padding: dp(5)
                    pos_hint: { 'center_x': 0.5}
                    on_release: root.add_card()